# CMake generated Testfile for 
# Source directory: D:/self/library/lpng
# Build directory: D:/self/library/lpng
# 
# This file includes the relevant testing commands required for 
# testing this directory and lists subdirectories to be tested as well.
if(CTEST_CONFIGURATION_TYPE MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
  add_test(pngtest "C:/Program Files/CMake/bin/cmake.exe" "-DLIBPNG=D:/self/library/lpng1644/Debug/libpng16d.dll" "-DTEST_COMMAND=D:/self/library/lpng1644/Debug/pngtest.exe" "-P" "D:/self/library/lpng1644/tests/pngtest.cmake")
  set_tests_properties(pngtest PROPERTIES  _BACKTRACE_TRIPLES "D:/self/library/lpng1644/CMakeLists.txt;797;add_test;D:/self/library/lpng1644/CMakeLists.txt;816;png_add_test;D:/self/library/lpng1644/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
  add_test(pngtest "C:/Program Files/CMake/bin/cmake.exe" "-DLIBPNG=D:/self/library/lpng1644/Release/libpng16.dll" "-DTEST_COMMAND=D:/self/library/lpng1644/Release/pngtest.exe" "-P" "D:/self/library/lpng1644/tests/pngtest.cmake")
  set_tests_properties(pngtest PROPERTIES  _BACKTRACE_TRIPLES "D:/self/library/lpng1644/CMakeLists.txt;797;add_test;D:/self/library/lpng1644/CMakeLists.txt;816;png_add_test;D:/self/library/lpng1644/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Mm][Ii][Nn][Ss][Ii][Zz][Ee][Rr][Ee][Ll])$")
  add_test(pngtest "C:/Program Files/CMake/bin/cmake.exe" "-DLIBPNG=D:/self/library/lpng1644/MinSizeRel/libpng16.dll" "-DTEST_COMMAND=D:/self/library/lpng1644/MinSizeRel/pngtest.exe" "-P" "D:/self/library/lpng1644/tests/pngtest.cmake")
  set_tests_properties(pngtest PROPERTIES  _BACKTRACE_TRIPLES "D:/self/library/lpng1644/CMakeLists.txt;797;add_test;D:/self/library/lpng1644/CMakeLists.txt;816;png_add_test;D:/self/library/lpng1644/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
  add_test(pngtest "C:/Program Files/CMake/bin/cmake.exe" "-DLIBPNG=D:/self/library/lpng1644/RelWithDebInfo/libpng16.dll" "-DTEST_COMMAND=D:/self/library/lpng1644/RelWithDebInfo/pngtest.exe" "-P" "D:/self/library/lpng1644/tests/pngtest.cmake")
  set_tests_properties(pngtest PROPERTIES  _BACKTRACE_TRIPLES "D:/self/library/lpng1644/CMakeLists.txt;797;add_test;D:/self/library/lpng1644/CMakeLists.txt;816;png_add_test;D:/self/library/lpng1644/CMakeLists.txt;0;")
else()
  add_test(pngtest NOT_AVAILABLE)
endif()
if(CTEST_CONFIGURATION_TYPE MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
  add_test(pngvalid-gamma-16-to-8 "C:/Program Files/CMake/bin/cmake.exe" "-DLIBPNG=D:/self/library/lpng1644/Debug/libpng16d.dll" "-DTEST_COMMAND=D:/self/library/lpng1644/Debug/pngvalid.exe" "-P" "D:/self/library/lpng1644/tests/pngvalid-gamma-16-to-8.cmake")
  set_tests_properties(pngvalid-gamma-16-to-8 PROPERTIES  _BACKTRACE_TRIPLES "D:/self/library/lpng1644/CMakeLists.txt;797;add_test;D:/self/library/lpng1644/CMakeLists.txt;823;png_add_test;D:/self/library/lpng1644/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
  add_test(pngvalid-gamma-16-to-8 "C:/Program Files/CMake/bin/cmake.exe" "-DLIBPNG=D:/self/library/lpng1644/Release/libpng16.dll" "-DTEST_COMMAND=D:/self/library/lpng1644/Release/pngvalid.exe" "-P" "D:/self/library/lpng1644/tests/pngvalid-gamma-16-to-8.cmake")
  set_tests_properties(pngvalid-gamma-16-to-8 PROPERTIES  _BACKTRACE_TRIPLES "D:/self/library/lpng1644/CMakeLists.txt;797;add_test;D:/self/library/lpng1644/CMakeLists.txt;823;png_add_test;D:/self/library/lpng1644/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Mm][Ii][Nn][Ss][Ii][Zz][Ee][Rr][Ee][Ll])$")
  add_test(pngvalid-gamma-16-to-8 "C:/Program Files/CMake/bin/cmake.exe" "-DLIBPNG=D:/self/library/lpng1644/MinSizeRel/libpng16.dll" "-DTEST_COMMAND=D:/self/library/lpng1644/MinSizeRel/pngvalid.exe" "-P" "D:/self/library/lpng1644/tests/pngvalid-gamma-16-to-8.cmake")
  set_tests_properties(pngvalid-gamma-16-to-8 PROPERTIES  _BACKTRACE_TRIPLES "D:/self/library/lpng1644/CMakeLists.txt;797;add_test;D:/self/library/lpng1644/CMakeLists.txt;823;png_add_test;D:/self/library/lpng1644/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
  add_test(pngvalid-gamma-16-to-8 "C:/Program Files/CMake/bin/cmake.exe" "-DLIBPNG=D:/self/library/lpng1644/RelWithDebInfo/libpng16.dll" "-DTEST_COMMAND=D:/self/library/lpng1644/RelWithDebInfo/pngvalid.exe" "-P" "D:/self/library/lpng1644/tests/pngvalid-gamma-16-to-8.cmake")
  set_tests_properties(pngvalid-gamma-16-to-8 PROPERTIES  _BACKTRACE_TRIPLES "D:/self/library/lpng1644/CMakeLists.txt;797;add_test;D:/self/library/lpng1644/CMakeLists.txt;823;png_add_test;D:/self/library/lpng1644/CMakeLists.txt;0;")
else()
  add_test(pngvalid-gamma-16-to-8 NOT_AVAILABLE)
endif()
if(CTEST_CONFIGURATION_TYPE MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
  add_test(pngvalid-gamma-alpha-mode "C:/Program Files/CMake/bin/cmake.exe" "-DLIBPNG=D:/self/library/lpng1644/Debug/libpng16d.dll" "-DTEST_COMMAND=D:/self/library/lpng1644/Debug/pngvalid.exe" "-P" "D:/self/library/lpng1644/tests/pngvalid-gamma-alpha-mode.cmake")
  set_tests_properties(pngvalid-gamma-alpha-mode PROPERTIES  _BACKTRACE_TRIPLES "D:/self/library/lpng1644/CMakeLists.txt;797;add_test;D:/self/library/lpng1644/CMakeLists.txt;826;png_add_test;D:/self/library/lpng1644/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
  add_test(pngvalid-gamma-alpha-mode "C:/Program Files/CMake/bin/cmake.exe" "-DLIBPNG=D:/self/library/lpng1644/Release/libpng16.dll" "-DTEST_COMMAND=D:/self/library/lpng1644/Release/pngvalid.exe" "-P" "D:/self/library/lpng1644/tests/pngvalid-gamma-alpha-mode.cmake")
  set_tests_properties(pngvalid-gamma-alpha-mode PROPERTIES  _BACKTRACE_TRIPLES "D:/self/library/lpng1644/CMakeLists.txt;797;add_test;D:/self/library/lpng1644/CMakeLists.txt;826;png_add_test;D:/self/library/lpng1644/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Mm][Ii][Nn][Ss][Ii][Zz][Ee][Rr][Ee][Ll])$")
  add_test(pngvalid-gamma-alpha-mode "C:/Program Files/CMake/bin/cmake.exe" "-DLIBPNG=D:/self/library/lpng1644/MinSizeRel/libpng16.dll" "-DTEST_COMMAND=D:/self/library/lpng1644/MinSizeRel/pngvalid.exe" "-P" "D:/self/library/lpng1644/tests/pngvalid-gamma-alpha-mode.cmake")
  set_tests_properties(pngvalid-gamma-alpha-mode PROPERTIES  _BACKTRACE_TRIPLES "D:/self/library/lpng1644/CMakeLists.txt;797;add_test;D:/self/library/lpng1644/CMakeLists.txt;826;png_add_test;D:/self/library/lpng1644/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
  add_test(pngvalid-gamma-alpha-mode "C:/Program Files/CMake/bin/cmake.exe" "-DLIBPNG=D:/self/library/lpng1644/RelWithDebInfo/libpng16.dll" "-DTEST_COMMAND=D:/self/library/lpng1644/RelWithDebInfo/pngvalid.exe" "-P" "D:/self/library/lpng1644/tests/pngvalid-gamma-alpha-mode.cmake")
  set_tests_properties(pngvalid-gamma-alpha-mode PROPERTIES  _BACKTRACE_TRIPLES "D:/self/library/lpng1644/CMakeLists.txt;797;add_test;D:/self/library/lpng1644/CMakeLists.txt;826;png_add_test;D:/self/library/lpng1644/CMakeLists.txt;0;")
else()
  add_test(pngvalid-gamma-alpha-mode NOT_AVAILABLE)
endif()
if(CTEST_CONFIGURATION_TYPE MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
  add_test(pngvalid-gamma-background "C:/Program Files/CMake/bin/cmake.exe" "-DLIBPNG=D:/self/library/lpng1644/Debug/libpng16d.dll" "-DTEST_COMMAND=D:/self/library/lpng1644/Debug/pngvalid.exe" "-P" "D:/self/library/lpng1644/tests/pngvalid-gamma-background.cmake")
  set_tests_properties(pngvalid-gamma-background PROPERTIES  _BACKTRACE_TRIPLES "D:/self/library/lpng1644/CMakeLists.txt;797;add_test;D:/self/library/lpng1644/CMakeLists.txt;829;png_add_test;D:/self/library/lpng1644/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
  add_test(pngvalid-gamma-background "C:/Program Files/CMake/bin/cmake.exe" "-DLIBPNG=D:/self/library/lpng1644/Release/libpng16.dll" "-DTEST_COMMAND=D:/self/library/lpng1644/Release/pngvalid.exe" "-P" "D:/self/library/lpng1644/tests/pngvalid-gamma-background.cmake")
  set_tests_properties(pngvalid-gamma-background PROPERTIES  _BACKTRACE_TRIPLES "D:/self/library/lpng1644/CMakeLists.txt;797;add_test;D:/self/library/lpng1644/CMakeLists.txt;829;png_add_test;D:/self/library/lpng1644/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Mm][Ii][Nn][Ss][Ii][Zz][Ee][Rr][Ee][Ll])$")
  add_test(pngvalid-gamma-background "C:/Program Files/CMake/bin/cmake.exe" "-DLIBPNG=D:/self/library/lpng1644/MinSizeRel/libpng16.dll" "-DTEST_COMMAND=D:/self/library/lpng1644/MinSizeRel/pngvalid.exe" "-P" "D:/self/library/lpng1644/tests/pngvalid-gamma-background.cmake")
  set_tests_properties(pngvalid-gamma-background PROPERTIES  _BACKTRACE_TRIPLES "D:/self/library/lpng1644/CMakeLists.txt;797;add_test;D:/self/library/lpng1644/CMakeLists.txt;829;png_add_test;D:/self/library/lpng1644/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
  add_test(pngvalid-gamma-background "C:/Program Files/CMake/bin/cmake.exe" "-DLIBPNG=D:/self/library/lpng1644/RelWithDebInfo/libpng16.dll" "-DTEST_COMMAND=D:/self/library/lpng1644/RelWithDebInfo/pngvalid.exe" "-P" "D:/self/library/lpng1644/tests/pngvalid-gamma-background.cmake")
  set_tests_properties(pngvalid-gamma-background PROPERTIES  _BACKTRACE_TRIPLES "D:/self/library/lpng1644/CMakeLists.txt;797;add_test;D:/self/library/lpng1644/CMakeLists.txt;829;png_add_test;D:/self/library/lpng1644/CMakeLists.txt;0;")
else()
  add_test(pngvalid-gamma-background NOT_AVAILABLE)
endif()
if(CTEST_CONFIGURATION_TYPE MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
  add_test(pngvalid-gamma-expand16-alpha-mode "C:/Program Files/CMake/bin/cmake.exe" "-DLIBPNG=D:/self/library/lpng1644/Debug/libpng16d.dll" "-DTEST_COMMAND=D:/self/library/lpng1644/Debug/pngvalid.exe" "-P" "D:/self/library/lpng1644/tests/pngvalid-gamma-expand16-alpha-mode.cmake")
  set_tests_properties(pngvalid-gamma-expand16-alpha-mode PROPERTIES  _BACKTRACE_TRIPLES "D:/self/library/lpng1644/CMakeLists.txt;797;add_test;D:/self/library/lpng1644/CMakeLists.txt;832;png_add_test;D:/self/library/lpng1644/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
  add_test(pngvalid-gamma-expand16-alpha-mode "C:/Program Files/CMake/bin/cmake.exe" "-DLIBPNG=D:/self/library/lpng1644/Release/libpng16.dll" "-DTEST_COMMAND=D:/self/library/lpng1644/Release/pngvalid.exe" "-P" "D:/self/library/lpng1644/tests/pngvalid-gamma-expand16-alpha-mode.cmake")
  set_tests_properties(pngvalid-gamma-expand16-alpha-mode PROPERTIES  _BACKTRACE_TRIPLES "D:/self/library/lpng1644/CMakeLists.txt;797;add_test;D:/self/library/lpng1644/CMakeLists.txt;832;png_add_test;D:/self/library/lpng1644/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Mm][Ii][Nn][Ss][Ii][Zz][Ee][Rr][Ee][Ll])$")
  add_test(pngvalid-gamma-expand16-alpha-mode "C:/Program Files/CMake/bin/cmake.exe" "-DLIBPNG=D:/self/library/lpng1644/MinSizeRel/libpng16.dll" "-DTEST_COMMAND=D:/self/library/lpng1644/MinSizeRel/pngvalid.exe" "-P" "D:/self/library/lpng1644/tests/pngvalid-gamma-expand16-alpha-mode.cmake")
  set_tests_properties(pngvalid-gamma-expand16-alpha-mode PROPERTIES  _BACKTRACE_TRIPLES "D:/self/library/lpng1644/CMakeLists.txt;797;add_test;D:/self/library/lpng1644/CMakeLists.txt;832;png_add_test;D:/self/library/lpng1644/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
  add_test(pngvalid-gamma-expand16-alpha-mode "C:/Program Files/CMake/bin/cmake.exe" "-DLIBPNG=D:/self/library/lpng1644/RelWithDebInfo/libpng16.dll" "-DTEST_COMMAND=D:/self/library/lpng1644/RelWithDebInfo/pngvalid.exe" "-P" "D:/self/library/lpng1644/tests/pngvalid-gamma-expand16-alpha-mode.cmake")
  set_tests_properties(pngvalid-gamma-expand16-alpha-mode PROPERTIES  _BACKTRACE_TRIPLES "D:/self/library/lpng1644/CMakeLists.txt;797;add_test;D:/self/library/lpng1644/CMakeLists.txt;832;png_add_test;D:/self/library/lpng1644/CMakeLists.txt;0;")
else()
  add_test(pngvalid-gamma-expand16-alpha-mode NOT_AVAILABLE)
endif()
if(CTEST_CONFIGURATION_TYPE MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
  add_test(pngvalid-gamma-expand16-background "C:/Program Files/CMake/bin/cmake.exe" "-DLIBPNG=D:/self/library/lpng1644/Debug/libpng16d.dll" "-DTEST_COMMAND=D:/self/library/lpng1644/Debug/pngvalid.exe" "-P" "D:/self/library/lpng1644/tests/pngvalid-gamma-expand16-background.cmake")
  set_tests_properties(pngvalid-gamma-expand16-background PROPERTIES  _BACKTRACE_TRIPLES "D:/self/library/lpng1644/CMakeLists.txt;797;add_test;D:/self/library/lpng1644/CMakeLists.txt;835;png_add_test;D:/self/library/lpng1644/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
  add_test(pngvalid-gamma-expand16-background "C:/Program Files/CMake/bin/cmake.exe" "-DLIBPNG=D:/self/library/lpng1644/Release/libpng16.dll" "-DTEST_COMMAND=D:/self/library/lpng1644/Release/pngvalid.exe" "-P" "D:/self/library/lpng1644/tests/pngvalid-gamma-expand16-background.cmake")
  set_tests_properties(pngvalid-gamma-expand16-background PROPERTIES  _BACKTRACE_TRIPLES "D:/self/library/lpng1644/CMakeLists.txt;797;add_test;D:/self/library/lpng1644/CMakeLists.txt;835;png_add_test;D:/self/library/lpng1644/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Mm][Ii][Nn][Ss][Ii][Zz][Ee][Rr][Ee][Ll])$")
  add_test(pngvalid-gamma-expand16-background "C:/Program Files/CMake/bin/cmake.exe" "-DLIBPNG=D:/self/library/lpng1644/MinSizeRel/libpng16.dll" "-DTEST_COMMAND=D:/self/library/lpng1644/MinSizeRel/pngvalid.exe" "-P" "D:/self/library/lpng1644/tests/pngvalid-gamma-expand16-background.cmake")
  set_tests_properties(pngvalid-gamma-expand16-background PROPERTIES  _BACKTRACE_TRIPLES "D:/self/library/lpng1644/CMakeLists.txt;797;add_test;D:/self/library/lpng1644/CMakeLists.txt;835;png_add_test;D:/self/library/lpng1644/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
  add_test(pngvalid-gamma-expand16-background "C:/Program Files/CMake/bin/cmake.exe" "-DLIBPNG=D:/self/library/lpng1644/RelWithDebInfo/libpng16.dll" "-DTEST_COMMAND=D:/self/library/lpng1644/RelWithDebInfo/pngvalid.exe" "-P" "D:/self/library/lpng1644/tests/pngvalid-gamma-expand16-background.cmake")
  set_tests_properties(pngvalid-gamma-expand16-background PROPERTIES  _BACKTRACE_TRIPLES "D:/self/library/lpng1644/CMakeLists.txt;797;add_test;D:/self/library/lpng1644/CMakeLists.txt;835;png_add_test;D:/self/library/lpng1644/CMakeLists.txt;0;")
else()
  add_test(pngvalid-gamma-expand16-background NOT_AVAILABLE)
endif()
if(CTEST_CONFIGURATION_TYPE MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
  add_test(pngvalid-gamma-expand16-transform "C:/Program Files/CMake/bin/cmake.exe" "-DLIBPNG=D:/self/library/lpng1644/Debug/libpng16d.dll" "-DTEST_COMMAND=D:/self/library/lpng1644/Debug/pngvalid.exe" "-P" "D:/self/library/lpng1644/tests/pngvalid-gamma-expand16-transform.cmake")
  set_tests_properties(pngvalid-gamma-expand16-transform PROPERTIES  _BACKTRACE_TRIPLES "D:/self/library/lpng1644/CMakeLists.txt;797;add_test;D:/self/library/lpng1644/CMakeLists.txt;838;png_add_test;D:/self/library/lpng1644/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
  add_test(pngvalid-gamma-expand16-transform "C:/Program Files/CMake/bin/cmake.exe" "-DLIBPNG=D:/self/library/lpng1644/Release/libpng16.dll" "-DTEST_COMMAND=D:/self/library/lpng1644/Release/pngvalid.exe" "-P" "D:/self/library/lpng1644/tests/pngvalid-gamma-expand16-transform.cmake")
  set_tests_properties(pngvalid-gamma-expand16-transform PROPERTIES  _BACKTRACE_TRIPLES "D:/self/library/lpng1644/CMakeLists.txt;797;add_test;D:/self/library/lpng1644/CMakeLists.txt;838;png_add_test;D:/self/library/lpng1644/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Mm][Ii][Nn][Ss][Ii][Zz][Ee][Rr][Ee][Ll])$")
  add_test(pngvalid-gamma-expand16-transform "C:/Program Files/CMake/bin/cmake.exe" "-DLIBPNG=D:/self/library/lpng1644/MinSizeRel/libpng16.dll" "-DTEST_COMMAND=D:/self/library/lpng1644/MinSizeRel/pngvalid.exe" "-P" "D:/self/library/lpng1644/tests/pngvalid-gamma-expand16-transform.cmake")
  set_tests_properties(pngvalid-gamma-expand16-transform PROPERTIES  _BACKTRACE_TRIPLES "D:/self/library/lpng1644/CMakeLists.txt;797;add_test;D:/self/library/lpng1644/CMakeLists.txt;838;png_add_test;D:/self/library/lpng1644/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
  add_test(pngvalid-gamma-expand16-transform "C:/Program Files/CMake/bin/cmake.exe" "-DLIBPNG=D:/self/library/lpng1644/RelWithDebInfo/libpng16.dll" "-DTEST_COMMAND=D:/self/library/lpng1644/RelWithDebInfo/pngvalid.exe" "-P" "D:/self/library/lpng1644/tests/pngvalid-gamma-expand16-transform.cmake")
  set_tests_properties(pngvalid-gamma-expand16-transform PROPERTIES  _BACKTRACE_TRIPLES "D:/self/library/lpng1644/CMakeLists.txt;797;add_test;D:/self/library/lpng1644/CMakeLists.txt;838;png_add_test;D:/self/library/lpng1644/CMakeLists.txt;0;")
else()
  add_test(pngvalid-gamma-expand16-transform NOT_AVAILABLE)
endif()
if(CTEST_CONFIGURATION_TYPE MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
  add_test(pngvalid-gamma-sbit "C:/Program Files/CMake/bin/cmake.exe" "-DLIBPNG=D:/self/library/lpng1644/Debug/libpng16d.dll" "-DTEST_COMMAND=D:/self/library/lpng1644/Debug/pngvalid.exe" "-P" "D:/self/library/lpng1644/tests/pngvalid-gamma-sbit.cmake")
  set_tests_properties(pngvalid-gamma-sbit PROPERTIES  _BACKTRACE_TRIPLES "D:/self/library/lpng1644/CMakeLists.txt;797;add_test;D:/self/library/lpng1644/CMakeLists.txt;841;png_add_test;D:/self/library/lpng1644/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
  add_test(pngvalid-gamma-sbit "C:/Program Files/CMake/bin/cmake.exe" "-DLIBPNG=D:/self/library/lpng1644/Release/libpng16.dll" "-DTEST_COMMAND=D:/self/library/lpng1644/Release/pngvalid.exe" "-P" "D:/self/library/lpng1644/tests/pngvalid-gamma-sbit.cmake")
  set_tests_properties(pngvalid-gamma-sbit PROPERTIES  _BACKTRACE_TRIPLES "D:/self/library/lpng1644/CMakeLists.txt;797;add_test;D:/self/library/lpng1644/CMakeLists.txt;841;png_add_test;D:/self/library/lpng1644/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Mm][Ii][Nn][Ss][Ii][Zz][Ee][Rr][Ee][Ll])$")
  add_test(pngvalid-gamma-sbit "C:/Program Files/CMake/bin/cmake.exe" "-DLIBPNG=D:/self/library/lpng1644/MinSizeRel/libpng16.dll" "-DTEST_COMMAND=D:/self/library/lpng1644/MinSizeRel/pngvalid.exe" "-P" "D:/self/library/lpng1644/tests/pngvalid-gamma-sbit.cmake")
  set_tests_properties(pngvalid-gamma-sbit PROPERTIES  _BACKTRACE_TRIPLES "D:/self/library/lpng1644/CMakeLists.txt;797;add_test;D:/self/library/lpng1644/CMakeLists.txt;841;png_add_test;D:/self/library/lpng1644/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
  add_test(pngvalid-gamma-sbit "C:/Program Files/CMake/bin/cmake.exe" "-DLIBPNG=D:/self/library/lpng1644/RelWithDebInfo/libpng16.dll" "-DTEST_COMMAND=D:/self/library/lpng1644/RelWithDebInfo/pngvalid.exe" "-P" "D:/self/library/lpng1644/tests/pngvalid-gamma-sbit.cmake")
  set_tests_properties(pngvalid-gamma-sbit PROPERTIES  _BACKTRACE_TRIPLES "D:/self/library/lpng1644/CMakeLists.txt;797;add_test;D:/self/library/lpng1644/CMakeLists.txt;841;png_add_test;D:/self/library/lpng1644/CMakeLists.txt;0;")
else()
  add_test(pngvalid-gamma-sbit NOT_AVAILABLE)
endif()
if(CTEST_CONFIGURATION_TYPE MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
  add_test(pngvalid-gamma-threshold "C:/Program Files/CMake/bin/cmake.exe" "-DLIBPNG=D:/self/library/lpng1644/Debug/libpng16d.dll" "-DTEST_COMMAND=D:/self/library/lpng1644/Debug/pngvalid.exe" "-P" "D:/self/library/lpng1644/tests/pngvalid-gamma-threshold.cmake")
  set_tests_properties(pngvalid-gamma-threshold PROPERTIES  _BACKTRACE_TRIPLES "D:/self/library/lpng1644/CMakeLists.txt;797;add_test;D:/self/library/lpng1644/CMakeLists.txt;844;png_add_test;D:/self/library/lpng1644/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
  add_test(pngvalid-gamma-threshold "C:/Program Files/CMake/bin/cmake.exe" "-DLIBPNG=D:/self/library/lpng1644/Release/libpng16.dll" "-DTEST_COMMAND=D:/self/library/lpng1644/Release/pngvalid.exe" "-P" "D:/self/library/lpng1644/tests/pngvalid-gamma-threshold.cmake")
  set_tests_properties(pngvalid-gamma-threshold PROPERTIES  _BACKTRACE_TRIPLES "D:/self/library/lpng1644/CMakeLists.txt;797;add_test;D:/self/library/lpng1644/CMakeLists.txt;844;png_add_test;D:/self/library/lpng1644/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Mm][Ii][Nn][Ss][Ii][Zz][Ee][Rr][Ee][Ll])$")
  add_test(pngvalid-gamma-threshold "C:/Program Files/CMake/bin/cmake.exe" "-DLIBPNG=D:/self/library/lpng1644/MinSizeRel/libpng16.dll" "-DTEST_COMMAND=D:/self/library/lpng1644/MinSizeRel/pngvalid.exe" "-P" "D:/self/library/lpng1644/tests/pngvalid-gamma-threshold.cmake")
  set_tests_properties(pngvalid-gamma-threshold PROPERTIES  _BACKTRACE_TRIPLES "D:/self/library/lpng1644/CMakeLists.txt;797;add_test;D:/self/library/lpng1644/CMakeLists.txt;844;png_add_test;D:/self/library/lpng1644/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
  add_test(pngvalid-gamma-threshold "C:/Program Files/CMake/bin/cmake.exe" "-DLIBPNG=D:/self/library/lpng1644/RelWithDebInfo/libpng16.dll" "-DTEST_COMMAND=D:/self/library/lpng1644/RelWithDebInfo/pngvalid.exe" "-P" "D:/self/library/lpng1644/tests/pngvalid-gamma-threshold.cmake")
  set_tests_properties(pngvalid-gamma-threshold PROPERTIES  _BACKTRACE_TRIPLES "D:/self/library/lpng1644/CMakeLists.txt;797;add_test;D:/self/library/lpng1644/CMakeLists.txt;844;png_add_test;D:/self/library/lpng1644/CMakeLists.txt;0;")
else()
  add_test(pngvalid-gamma-threshold NOT_AVAILABLE)
endif()
if(CTEST_CONFIGURATION_TYPE MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
  add_test(pngvalid-gamma-transform "C:/Program Files/CMake/bin/cmake.exe" "-DLIBPNG=D:/self/library/lpng1644/Debug/libpng16d.dll" "-DTEST_COMMAND=D:/self/library/lpng1644/Debug/pngvalid.exe" "-P" "D:/self/library/lpng1644/tests/pngvalid-gamma-transform.cmake")
  set_tests_properties(pngvalid-gamma-transform PROPERTIES  _BACKTRACE_TRIPLES "D:/self/library/lpng1644/CMakeLists.txt;797;add_test;D:/self/library/lpng1644/CMakeLists.txt;847;png_add_test;D:/self/library/lpng1644/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
  add_test(pngvalid-gamma-transform "C:/Program Files/CMake/bin/cmake.exe" "-DLIBPNG=D:/self/library/lpng1644/Release/libpng16.dll" "-DTEST_COMMAND=D:/self/library/lpng1644/Release/pngvalid.exe" "-P" "D:/self/library/lpng1644/tests/pngvalid-gamma-transform.cmake")
  set_tests_properties(pngvalid-gamma-transform PROPERTIES  _BACKTRACE_TRIPLES "D:/self/library/lpng1644/CMakeLists.txt;797;add_test;D:/self/library/lpng1644/CMakeLists.txt;847;png_add_test;D:/self/library/lpng1644/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Mm][Ii][Nn][Ss][Ii][Zz][Ee][Rr][Ee][Ll])$")
  add_test(pngvalid-gamma-transform "C:/Program Files/CMake/bin/cmake.exe" "-DLIBPNG=D:/self/library/lpng1644/MinSizeRel/libpng16.dll" "-DTEST_COMMAND=D:/self/library/lpng1644/MinSizeRel/pngvalid.exe" "-P" "D:/self/library/lpng1644/tests/pngvalid-gamma-transform.cmake")
  set_tests_properties(pngvalid-gamma-transform PROPERTIES  _BACKTRACE_TRIPLES "D:/self/library/lpng1644/CMakeLists.txt;797;add_test;D:/self/library/lpng1644/CMakeLists.txt;847;png_add_test;D:/self/library/lpng1644/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
  add_test(pngvalid-gamma-transform "C:/Program Files/CMake/bin/cmake.exe" "-DLIBPNG=D:/self/library/lpng1644/RelWithDebInfo/libpng16.dll" "-DTEST_COMMAND=D:/self/library/lpng1644/RelWithDebInfo/pngvalid.exe" "-P" "D:/self/library/lpng1644/tests/pngvalid-gamma-transform.cmake")
  set_tests_properties(pngvalid-gamma-transform PROPERTIES  _BACKTRACE_TRIPLES "D:/self/library/lpng1644/CMakeLists.txt;797;add_test;D:/self/library/lpng1644/CMakeLists.txt;847;png_add_test;D:/self/library/lpng1644/CMakeLists.txt;0;")
else()
  add_test(pngvalid-gamma-transform NOT_AVAILABLE)
endif()
if(CTEST_CONFIGURATION_TYPE MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
  add_test(pngvalid-progressive-interlace-standard "C:/Program Files/CMake/bin/cmake.exe" "-DLIBPNG=D:/self/library/lpng1644/Debug/libpng16d.dll" "-DTEST_COMMAND=D:/self/library/lpng1644/Debug/pngvalid.exe" "-P" "D:/self/library/lpng1644/tests/pngvalid-progressive-interlace-standard.cmake")
  set_tests_properties(pngvalid-progressive-interlace-standard PROPERTIES  _BACKTRACE_TRIPLES "D:/self/library/lpng1644/CMakeLists.txt;797;add_test;D:/self/library/lpng1644/CMakeLists.txt;850;png_add_test;D:/self/library/lpng1644/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
  add_test(pngvalid-progressive-interlace-standard "C:/Program Files/CMake/bin/cmake.exe" "-DLIBPNG=D:/self/library/lpng1644/Release/libpng16.dll" "-DTEST_COMMAND=D:/self/library/lpng1644/Release/pngvalid.exe" "-P" "D:/self/library/lpng1644/tests/pngvalid-progressive-interlace-standard.cmake")
  set_tests_properties(pngvalid-progressive-interlace-standard PROPERTIES  _BACKTRACE_TRIPLES "D:/self/library/lpng1644/CMakeLists.txt;797;add_test;D:/self/library/lpng1644/CMakeLists.txt;850;png_add_test;D:/self/library/lpng1644/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Mm][Ii][Nn][Ss][Ii][Zz][Ee][Rr][Ee][Ll])$")
  add_test(pngvalid-progressive-interlace-standard "C:/Program Files/CMake/bin/cmake.exe" "-DLIBPNG=D:/self/library/lpng1644/MinSizeRel/libpng16.dll" "-DTEST_COMMAND=D:/self/library/lpng1644/MinSizeRel/pngvalid.exe" "-P" "D:/self/library/lpng1644/tests/pngvalid-progressive-interlace-standard.cmake")
  set_tests_properties(pngvalid-progressive-interlace-standard PROPERTIES  _BACKTRACE_TRIPLES "D:/self/library/lpng1644/CMakeLists.txt;797;add_test;D:/self/library/lpng1644/CMakeLists.txt;850;png_add_test;D:/self/library/lpng1644/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
  add_test(pngvalid-progressive-interlace-standard "C:/Program Files/CMake/bin/cmake.exe" "-DLIBPNG=D:/self/library/lpng1644/RelWithDebInfo/libpng16.dll" "-DTEST_COMMAND=D:/self/library/lpng1644/RelWithDebInfo/pngvalid.exe" "-P" "D:/self/library/lpng1644/tests/pngvalid-progressive-interlace-standard.cmake")
  set_tests_properties(pngvalid-progressive-interlace-standard PROPERTIES  _BACKTRACE_TRIPLES "D:/self/library/lpng1644/CMakeLists.txt;797;add_test;D:/self/library/lpng1644/CMakeLists.txt;850;png_add_test;D:/self/library/lpng1644/CMakeLists.txt;0;")
else()
  add_test(pngvalid-progressive-interlace-standard NOT_AVAILABLE)
endif()
if(CTEST_CONFIGURATION_TYPE MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
  add_test(pngvalid-progressive-size "C:/Program Files/CMake/bin/cmake.exe" "-DLIBPNG=D:/self/library/lpng1644/Debug/libpng16d.dll" "-DTEST_COMMAND=D:/self/library/lpng1644/Debug/pngvalid.exe" "-P" "D:/self/library/lpng1644/tests/pngvalid-progressive-size.cmake")
  set_tests_properties(pngvalid-progressive-size PROPERTIES  _BACKTRACE_TRIPLES "D:/self/library/lpng1644/CMakeLists.txt;797;add_test;D:/self/library/lpng1644/CMakeLists.txt;853;png_add_test;D:/self/library/lpng1644/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
  add_test(pngvalid-progressive-size "C:/Program Files/CMake/bin/cmake.exe" "-DLIBPNG=D:/self/library/lpng1644/Release/libpng16.dll" "-DTEST_COMMAND=D:/self/library/lpng1644/Release/pngvalid.exe" "-P" "D:/self/library/lpng1644/tests/pngvalid-progressive-size.cmake")
  set_tests_properties(pngvalid-progressive-size PROPERTIES  _BACKTRACE_TRIPLES "D:/self/library/lpng1644/CMakeLists.txt;797;add_test;D:/self/library/lpng1644/CMakeLists.txt;853;png_add_test;D:/self/library/lpng1644/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Mm][Ii][Nn][Ss][Ii][Zz][Ee][Rr][Ee][Ll])$")
  add_test(pngvalid-progressive-size "C:/Program Files/CMake/bin/cmake.exe" "-DLIBPNG=D:/self/library/lpng1644/MinSizeRel/libpng16.dll" "-DTEST_COMMAND=D:/self/library/lpng1644/MinSizeRel/pngvalid.exe" "-P" "D:/self/library/lpng1644/tests/pngvalid-progressive-size.cmake")
  set_tests_properties(pngvalid-progressive-size PROPERTIES  _BACKTRACE_TRIPLES "D:/self/library/lpng1644/CMakeLists.txt;797;add_test;D:/self/library/lpng1644/CMakeLists.txt;853;png_add_test;D:/self/library/lpng1644/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
  add_test(pngvalid-progressive-size "C:/Program Files/CMake/bin/cmake.exe" "-DLIBPNG=D:/self/library/lpng1644/RelWithDebInfo/libpng16.dll" "-DTEST_COMMAND=D:/self/library/lpng1644/RelWithDebInfo/pngvalid.exe" "-P" "D:/self/library/lpng1644/tests/pngvalid-progressive-size.cmake")
  set_tests_properties(pngvalid-progressive-size PROPERTIES  _BACKTRACE_TRIPLES "D:/self/library/lpng1644/CMakeLists.txt;797;add_test;D:/self/library/lpng1644/CMakeLists.txt;853;png_add_test;D:/self/library/lpng1644/CMakeLists.txt;0;")
else()
  add_test(pngvalid-progressive-size NOT_AVAILABLE)
endif()
if(CTEST_CONFIGURATION_TYPE MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
  add_test(pngvalid-progressive-standard "C:/Program Files/CMake/bin/cmake.exe" "-DLIBPNG=D:/self/library/lpng1644/Debug/libpng16d.dll" "-DTEST_COMMAND=D:/self/library/lpng1644/Debug/pngvalid.exe" "-P" "D:/self/library/lpng1644/tests/pngvalid-progressive-standard.cmake")
  set_tests_properties(pngvalid-progressive-standard PROPERTIES  _BACKTRACE_TRIPLES "D:/self/library/lpng1644/CMakeLists.txt;797;add_test;D:/self/library/lpng1644/CMakeLists.txt;856;png_add_test;D:/self/library/lpng1644/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
  add_test(pngvalid-progressive-standard "C:/Program Files/CMake/bin/cmake.exe" "-DLIBPNG=D:/self/library/lpng1644/Release/libpng16.dll" "-DTEST_COMMAND=D:/self/library/lpng1644/Release/pngvalid.exe" "-P" "D:/self/library/lpng1644/tests/pngvalid-progressive-standard.cmake")
  set_tests_properties(pngvalid-progressive-standard PROPERTIES  _BACKTRACE_TRIPLES "D:/self/library/lpng1644/CMakeLists.txt;797;add_test;D:/self/library/lpng1644/CMakeLists.txt;856;png_add_test;D:/self/library/lpng1644/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Mm][Ii][Nn][Ss][Ii][Zz][Ee][Rr][Ee][Ll])$")
  add_test(pngvalid-progressive-standard "C:/Program Files/CMake/bin/cmake.exe" "-DLIBPNG=D:/self/library/lpng1644/MinSizeRel/libpng16.dll" "-DTEST_COMMAND=D:/self/library/lpng1644/MinSizeRel/pngvalid.exe" "-P" "D:/self/library/lpng1644/tests/pngvalid-progressive-standard.cmake")
  set_tests_properties(pngvalid-progressive-standard PROPERTIES  _BACKTRACE_TRIPLES "D:/self/library/lpng1644/CMakeLists.txt;797;add_test;D:/self/library/lpng1644/CMakeLists.txt;856;png_add_test;D:/self/library/lpng1644/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
  add_test(pngvalid-progressive-standard "C:/Program Files/CMake/bin/cmake.exe" "-DLIBPNG=D:/self/library/lpng1644/RelWithDebInfo/libpng16.dll" "-DTEST_COMMAND=D:/self/library/lpng1644/RelWithDebInfo/pngvalid.exe" "-P" "D:/self/library/lpng1644/tests/pngvalid-progressive-standard.cmake")
  set_tests_properties(pngvalid-progressive-standard PROPERTIES  _BACKTRACE_TRIPLES "D:/self/library/lpng1644/CMakeLists.txt;797;add_test;D:/self/library/lpng1644/CMakeLists.txt;856;png_add_test;D:/self/library/lpng1644/CMakeLists.txt;0;")
else()
  add_test(pngvalid-progressive-standard NOT_AVAILABLE)
endif()
if(CTEST_CONFIGURATION_TYPE MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
  add_test(pngvalid-standard "C:/Program Files/CMake/bin/cmake.exe" "-DLIBPNG=D:/self/library/lpng1644/Debug/libpng16d.dll" "-DTEST_COMMAND=D:/self/library/lpng1644/Debug/pngvalid.exe" "-P" "D:/self/library/lpng1644/tests/pngvalid-standard.cmake")
  set_tests_properties(pngvalid-standard PROPERTIES  _BACKTRACE_TRIPLES "D:/self/library/lpng1644/CMakeLists.txt;797;add_test;D:/self/library/lpng1644/CMakeLists.txt;859;png_add_test;D:/self/library/lpng1644/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
  add_test(pngvalid-standard "C:/Program Files/CMake/bin/cmake.exe" "-DLIBPNG=D:/self/library/lpng1644/Release/libpng16.dll" "-DTEST_COMMAND=D:/self/library/lpng1644/Release/pngvalid.exe" "-P" "D:/self/library/lpng1644/tests/pngvalid-standard.cmake")
  set_tests_properties(pngvalid-standard PROPERTIES  _BACKTRACE_TRIPLES "D:/self/library/lpng1644/CMakeLists.txt;797;add_test;D:/self/library/lpng1644/CMakeLists.txt;859;png_add_test;D:/self/library/lpng1644/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Mm][Ii][Nn][Ss][Ii][Zz][Ee][Rr][Ee][Ll])$")
  add_test(pngvalid-standard "C:/Program Files/CMake/bin/cmake.exe" "-DLIBPNG=D:/self/library/lpng1644/MinSizeRel/libpng16.dll" "-DTEST_COMMAND=D:/self/library/lpng1644/MinSizeRel/pngvalid.exe" "-P" "D:/self/library/lpng1644/tests/pngvalid-standard.cmake")
  set_tests_properties(pngvalid-standard PROPERTIES  _BACKTRACE_TRIPLES "D:/self/library/lpng1644/CMakeLists.txt;797;add_test;D:/self/library/lpng1644/CMakeLists.txt;859;png_add_test;D:/self/library/lpng1644/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
  add_test(pngvalid-standard "C:/Program Files/CMake/bin/cmake.exe" "-DLIBPNG=D:/self/library/lpng1644/RelWithDebInfo/libpng16.dll" "-DTEST_COMMAND=D:/self/library/lpng1644/RelWithDebInfo/pngvalid.exe" "-P" "D:/self/library/lpng1644/tests/pngvalid-standard.cmake")
  set_tests_properties(pngvalid-standard PROPERTIES  _BACKTRACE_TRIPLES "D:/self/library/lpng1644/CMakeLists.txt;797;add_test;D:/self/library/lpng1644/CMakeLists.txt;859;png_add_test;D:/self/library/lpng1644/CMakeLists.txt;0;")
else()
  add_test(pngvalid-standard NOT_AVAILABLE)
endif()
if(CTEST_CONFIGURATION_TYPE MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
  add_test(pngvalid-transform "C:/Program Files/CMake/bin/cmake.exe" "-DLIBPNG=D:/self/library/lpng1644/Debug/libpng16d.dll" "-DTEST_COMMAND=D:/self/library/lpng1644/Debug/pngvalid.exe" "-P" "D:/self/library/lpng1644/tests/pngvalid-transform.cmake")
  set_tests_properties(pngvalid-transform PROPERTIES  _BACKTRACE_TRIPLES "D:/self/library/lpng1644/CMakeLists.txt;797;add_test;D:/self/library/lpng1644/CMakeLists.txt;862;png_add_test;D:/self/library/lpng1644/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
  add_test(pngvalid-transform "C:/Program Files/CMake/bin/cmake.exe" "-DLIBPNG=D:/self/library/lpng1644/Release/libpng16.dll" "-DTEST_COMMAND=D:/self/library/lpng1644/Release/pngvalid.exe" "-P" "D:/self/library/lpng1644/tests/pngvalid-transform.cmake")
  set_tests_properties(pngvalid-transform PROPERTIES  _BACKTRACE_TRIPLES "D:/self/library/lpng1644/CMakeLists.txt;797;add_test;D:/self/library/lpng1644/CMakeLists.txt;862;png_add_test;D:/self/library/lpng1644/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Mm][Ii][Nn][Ss][Ii][Zz][Ee][Rr][Ee][Ll])$")
  add_test(pngvalid-transform "C:/Program Files/CMake/bin/cmake.exe" "-DLIBPNG=D:/self/library/lpng1644/MinSizeRel/libpng16.dll" "-DTEST_COMMAND=D:/self/library/lpng1644/MinSizeRel/pngvalid.exe" "-P" "D:/self/library/lpng1644/tests/pngvalid-transform.cmake")
  set_tests_properties(pngvalid-transform PROPERTIES  _BACKTRACE_TRIPLES "D:/self/library/lpng1644/CMakeLists.txt;797;add_test;D:/self/library/lpng1644/CMakeLists.txt;862;png_add_test;D:/self/library/lpng1644/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
  add_test(pngvalid-transform "C:/Program Files/CMake/bin/cmake.exe" "-DLIBPNG=D:/self/library/lpng1644/RelWithDebInfo/libpng16.dll" "-DTEST_COMMAND=D:/self/library/lpng1644/RelWithDebInfo/pngvalid.exe" "-P" "D:/self/library/lpng1644/tests/pngvalid-transform.cmake")
  set_tests_properties(pngvalid-transform PROPERTIES  _BACKTRACE_TRIPLES "D:/self/library/lpng1644/CMakeLists.txt;797;add_test;D:/self/library/lpng1644/CMakeLists.txt;862;png_add_test;D:/self/library/lpng1644/CMakeLists.txt;0;")
else()
  add_test(pngvalid-transform NOT_AVAILABLE)
endif()
if(CTEST_CONFIGURATION_TYPE MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
  add_test(pngstest-1.8-none "C:/Program Files/CMake/bin/cmake.exe" "-DLIBPNG=D:/self/library/lpng1644/Debug/libpng16d.dll" "-DTEST_COMMAND=D:/self/library/lpng1644/Debug/pngstest.exe" "-P" "D:/self/library/lpng1644/tests/pngstest-1.8-none.cmake")
  set_tests_properties(pngstest-1.8-none PROPERTIES  _BACKTRACE_TRIPLES "D:/self/library/lpng1644/CMakeLists.txt;797;add_test;D:/self/library/lpng1644/CMakeLists.txt;914;png_add_test;D:/self/library/lpng1644/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
  add_test(pngstest-1.8-none "C:/Program Files/CMake/bin/cmake.exe" "-DLIBPNG=D:/self/library/lpng1644/Release/libpng16.dll" "-DTEST_COMMAND=D:/self/library/lpng1644/Release/pngstest.exe" "-P" "D:/self/library/lpng1644/tests/pngstest-1.8-none.cmake")
  set_tests_properties(pngstest-1.8-none PROPERTIES  _BACKTRACE_TRIPLES "D:/self/library/lpng1644/CMakeLists.txt;797;add_test;D:/self/library/lpng1644/CMakeLists.txt;914;png_add_test;D:/self/library/lpng1644/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Mm][Ii][Nn][Ss][Ii][Zz][Ee][Rr][Ee][Ll])$")
  add_test(pngstest-1.8-none "C:/Program Files/CMake/bin/cmake.exe" "-DLIBPNG=D:/self/library/lpng1644/MinSizeRel/libpng16.dll" "-DTEST_COMMAND=D:/self/library/lpng1644/MinSizeRel/pngstest.exe" "-P" "D:/self/library/lpng1644/tests/pngstest-1.8-none.cmake")
  set_tests_properties(pngstest-1.8-none PROPERTIES  _BACKTRACE_TRIPLES "D:/self/library/lpng1644/CMakeLists.txt;797;add_test;D:/self/library/lpng1644/CMakeLists.txt;914;png_add_test;D:/self/library/lpng1644/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
  add_test(pngstest-1.8-none "C:/Program Files/CMake/bin/cmake.exe" "-DLIBPNG=D:/self/library/lpng1644/RelWithDebInfo/libpng16.dll" "-DTEST_COMMAND=D:/self/library/lpng1644/RelWithDebInfo/pngstest.exe" "-P" "D:/self/library/lpng1644/tests/pngstest-1.8-none.cmake")
  set_tests_properties(pngstest-1.8-none PROPERTIES  _BACKTRACE_TRIPLES "D:/self/library/lpng1644/CMakeLists.txt;797;add_test;D:/self/library/lpng1644/CMakeLists.txt;914;png_add_test;D:/self/library/lpng1644/CMakeLists.txt;0;")
else()
  add_test(pngstest-1.8-none NOT_AVAILABLE)
endif()
if(CTEST_CONFIGURATION_TYPE MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
  add_test(pngstest-1.8-alpha "C:/Program Files/CMake/bin/cmake.exe" "-DLIBPNG=D:/self/library/lpng1644/Debug/libpng16d.dll" "-DTEST_COMMAND=D:/self/library/lpng1644/Debug/pngstest.exe" "-P" "D:/self/library/lpng1644/tests/pngstest-1.8-alpha.cmake")
  set_tests_properties(pngstest-1.8-alpha PROPERTIES  _BACKTRACE_TRIPLES "D:/self/library/lpng1644/CMakeLists.txt;797;add_test;D:/self/library/lpng1644/CMakeLists.txt;914;png_add_test;D:/self/library/lpng1644/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
  add_test(pngstest-1.8-alpha "C:/Program Files/CMake/bin/cmake.exe" "-DLIBPNG=D:/self/library/lpng1644/Release/libpng16.dll" "-DTEST_COMMAND=D:/self/library/lpng1644/Release/pngstest.exe" "-P" "D:/self/library/lpng1644/tests/pngstest-1.8-alpha.cmake")
  set_tests_properties(pngstest-1.8-alpha PROPERTIES  _BACKTRACE_TRIPLES "D:/self/library/lpng1644/CMakeLists.txt;797;add_test;D:/self/library/lpng1644/CMakeLists.txt;914;png_add_test;D:/self/library/lpng1644/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Mm][Ii][Nn][Ss][Ii][Zz][Ee][Rr][Ee][Ll])$")
  add_test(pngstest-1.8-alpha "C:/Program Files/CMake/bin/cmake.exe" "-DLIBPNG=D:/self/library/lpng1644/MinSizeRel/libpng16.dll" "-DTEST_COMMAND=D:/self/library/lpng1644/MinSizeRel/pngstest.exe" "-P" "D:/self/library/lpng1644/tests/pngstest-1.8-alpha.cmake")
  set_tests_properties(pngstest-1.8-alpha PROPERTIES  _BACKTRACE_TRIPLES "D:/self/library/lpng1644/CMakeLists.txt;797;add_test;D:/self/library/lpng1644/CMakeLists.txt;914;png_add_test;D:/self/library/lpng1644/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
  add_test(pngstest-1.8-alpha "C:/Program Files/CMake/bin/cmake.exe" "-DLIBPNG=D:/self/library/lpng1644/RelWithDebInfo/libpng16.dll" "-DTEST_COMMAND=D:/self/library/lpng1644/RelWithDebInfo/pngstest.exe" "-P" "D:/self/library/lpng1644/tests/pngstest-1.8-alpha.cmake")
  set_tests_properties(pngstest-1.8-alpha PROPERTIES  _BACKTRACE_TRIPLES "D:/self/library/lpng1644/CMakeLists.txt;797;add_test;D:/self/library/lpng1644/CMakeLists.txt;914;png_add_test;D:/self/library/lpng1644/CMakeLists.txt;0;")
else()
  add_test(pngstest-1.8-alpha NOT_AVAILABLE)
endif()
if(CTEST_CONFIGURATION_TYPE MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
  add_test(pngstest-linear-none "C:/Program Files/CMake/bin/cmake.exe" "-DLIBPNG=D:/self/library/lpng1644/Debug/libpng16d.dll" "-DTEST_COMMAND=D:/self/library/lpng1644/Debug/pngstest.exe" "-P" "D:/self/library/lpng1644/tests/pngstest-linear-none.cmake")
  set_tests_properties(pngstest-linear-none PROPERTIES  _BACKTRACE_TRIPLES "D:/self/library/lpng1644/CMakeLists.txt;797;add_test;D:/self/library/lpng1644/CMakeLists.txt;914;png_add_test;D:/self/library/lpng1644/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
  add_test(pngstest-linear-none "C:/Program Files/CMake/bin/cmake.exe" "-DLIBPNG=D:/self/library/lpng1644/Release/libpng16.dll" "-DTEST_COMMAND=D:/self/library/lpng1644/Release/pngstest.exe" "-P" "D:/self/library/lpng1644/tests/pngstest-linear-none.cmake")
  set_tests_properties(pngstest-linear-none PROPERTIES  _BACKTRACE_TRIPLES "D:/self/library/lpng1644/CMakeLists.txt;797;add_test;D:/self/library/lpng1644/CMakeLists.txt;914;png_add_test;D:/self/library/lpng1644/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Mm][Ii][Nn][Ss][Ii][Zz][Ee][Rr][Ee][Ll])$")
  add_test(pngstest-linear-none "C:/Program Files/CMake/bin/cmake.exe" "-DLIBPNG=D:/self/library/lpng1644/MinSizeRel/libpng16.dll" "-DTEST_COMMAND=D:/self/library/lpng1644/MinSizeRel/pngstest.exe" "-P" "D:/self/library/lpng1644/tests/pngstest-linear-none.cmake")
  set_tests_properties(pngstest-linear-none PROPERTIES  _BACKTRACE_TRIPLES "D:/self/library/lpng1644/CMakeLists.txt;797;add_test;D:/self/library/lpng1644/CMakeLists.txt;914;png_add_test;D:/self/library/lpng1644/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
  add_test(pngstest-linear-none "C:/Program Files/CMake/bin/cmake.exe" "-DLIBPNG=D:/self/library/lpng1644/RelWithDebInfo/libpng16.dll" "-DTEST_COMMAND=D:/self/library/lpng1644/RelWithDebInfo/pngstest.exe" "-P" "D:/self/library/lpng1644/tests/pngstest-linear-none.cmake")
  set_tests_properties(pngstest-linear-none PROPERTIES  _BACKTRACE_TRIPLES "D:/self/library/lpng1644/CMakeLists.txt;797;add_test;D:/self/library/lpng1644/CMakeLists.txt;914;png_add_test;D:/self/library/lpng1644/CMakeLists.txt;0;")
else()
  add_test(pngstest-linear-none NOT_AVAILABLE)
endif()
if(CTEST_CONFIGURATION_TYPE MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
  add_test(pngstest-linear-alpha "C:/Program Files/CMake/bin/cmake.exe" "-DLIBPNG=D:/self/library/lpng1644/Debug/libpng16d.dll" "-DTEST_COMMAND=D:/self/library/lpng1644/Debug/pngstest.exe" "-P" "D:/self/library/lpng1644/tests/pngstest-linear-alpha.cmake")
  set_tests_properties(pngstest-linear-alpha PROPERTIES  _BACKTRACE_TRIPLES "D:/self/library/lpng1644/CMakeLists.txt;797;add_test;D:/self/library/lpng1644/CMakeLists.txt;914;png_add_test;D:/self/library/lpng1644/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
  add_test(pngstest-linear-alpha "C:/Program Files/CMake/bin/cmake.exe" "-DLIBPNG=D:/self/library/lpng1644/Release/libpng16.dll" "-DTEST_COMMAND=D:/self/library/lpng1644/Release/pngstest.exe" "-P" "D:/self/library/lpng1644/tests/pngstest-linear-alpha.cmake")
  set_tests_properties(pngstest-linear-alpha PROPERTIES  _BACKTRACE_TRIPLES "D:/self/library/lpng1644/CMakeLists.txt;797;add_test;D:/self/library/lpng1644/CMakeLists.txt;914;png_add_test;D:/self/library/lpng1644/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Mm][Ii][Nn][Ss][Ii][Zz][Ee][Rr][Ee][Ll])$")
  add_test(pngstest-linear-alpha "C:/Program Files/CMake/bin/cmake.exe" "-DLIBPNG=D:/self/library/lpng1644/MinSizeRel/libpng16.dll" "-DTEST_COMMAND=D:/self/library/lpng1644/MinSizeRel/pngstest.exe" "-P" "D:/self/library/lpng1644/tests/pngstest-linear-alpha.cmake")
  set_tests_properties(pngstest-linear-alpha PROPERTIES  _BACKTRACE_TRIPLES "D:/self/library/lpng1644/CMakeLists.txt;797;add_test;D:/self/library/lpng1644/CMakeLists.txt;914;png_add_test;D:/self/library/lpng1644/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
  add_test(pngstest-linear-alpha "C:/Program Files/CMake/bin/cmake.exe" "-DLIBPNG=D:/self/library/lpng1644/RelWithDebInfo/libpng16.dll" "-DTEST_COMMAND=D:/self/library/lpng1644/RelWithDebInfo/pngstest.exe" "-P" "D:/self/library/lpng1644/tests/pngstest-linear-alpha.cmake")
  set_tests_properties(pngstest-linear-alpha PROPERTIES  _BACKTRACE_TRIPLES "D:/self/library/lpng1644/CMakeLists.txt;797;add_test;D:/self/library/lpng1644/CMakeLists.txt;914;png_add_test;D:/self/library/lpng1644/CMakeLists.txt;0;")
else()
  add_test(pngstest-linear-alpha NOT_AVAILABLE)
endif()
if(CTEST_CONFIGURATION_TYPE MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
  add_test(pngstest-none-none "C:/Program Files/CMake/bin/cmake.exe" "-DLIBPNG=D:/self/library/lpng1644/Debug/libpng16d.dll" "-DTEST_COMMAND=D:/self/library/lpng1644/Debug/pngstest.exe" "-P" "D:/self/library/lpng1644/tests/pngstest-none-none.cmake")
  set_tests_properties(pngstest-none-none PROPERTIES  _BACKTRACE_TRIPLES "D:/self/library/lpng1644/CMakeLists.txt;797;add_test;D:/self/library/lpng1644/CMakeLists.txt;914;png_add_test;D:/self/library/lpng1644/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
  add_test(pngstest-none-none "C:/Program Files/CMake/bin/cmake.exe" "-DLIBPNG=D:/self/library/lpng1644/Release/libpng16.dll" "-DTEST_COMMAND=D:/self/library/lpng1644/Release/pngstest.exe" "-P" "D:/self/library/lpng1644/tests/pngstest-none-none.cmake")
  set_tests_properties(pngstest-none-none PROPERTIES  _BACKTRACE_TRIPLES "D:/self/library/lpng1644/CMakeLists.txt;797;add_test;D:/self/library/lpng1644/CMakeLists.txt;914;png_add_test;D:/self/library/lpng1644/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Mm][Ii][Nn][Ss][Ii][Zz][Ee][Rr][Ee][Ll])$")
  add_test(pngstest-none-none "C:/Program Files/CMake/bin/cmake.exe" "-DLIBPNG=D:/self/library/lpng1644/MinSizeRel/libpng16.dll" "-DTEST_COMMAND=D:/self/library/lpng1644/MinSizeRel/pngstest.exe" "-P" "D:/self/library/lpng1644/tests/pngstest-none-none.cmake")
  set_tests_properties(pngstest-none-none PROPERTIES  _BACKTRACE_TRIPLES "D:/self/library/lpng1644/CMakeLists.txt;797;add_test;D:/self/library/lpng1644/CMakeLists.txt;914;png_add_test;D:/self/library/lpng1644/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
  add_test(pngstest-none-none "C:/Program Files/CMake/bin/cmake.exe" "-DLIBPNG=D:/self/library/lpng1644/RelWithDebInfo/libpng16.dll" "-DTEST_COMMAND=D:/self/library/lpng1644/RelWithDebInfo/pngstest.exe" "-P" "D:/self/library/lpng1644/tests/pngstest-none-none.cmake")
  set_tests_properties(pngstest-none-none PROPERTIES  _BACKTRACE_TRIPLES "D:/self/library/lpng1644/CMakeLists.txt;797;add_test;D:/self/library/lpng1644/CMakeLists.txt;914;png_add_test;D:/self/library/lpng1644/CMakeLists.txt;0;")
else()
  add_test(pngstest-none-none NOT_AVAILABLE)
endif()
if(CTEST_CONFIGURATION_TYPE MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
  add_test(pngstest-none-alpha "C:/Program Files/CMake/bin/cmake.exe" "-DLIBPNG=D:/self/library/lpng1644/Debug/libpng16d.dll" "-DTEST_COMMAND=D:/self/library/lpng1644/Debug/pngstest.exe" "-P" "D:/self/library/lpng1644/tests/pngstest-none-alpha.cmake")
  set_tests_properties(pngstest-none-alpha PROPERTIES  _BACKTRACE_TRIPLES "D:/self/library/lpng1644/CMakeLists.txt;797;add_test;D:/self/library/lpng1644/CMakeLists.txt;914;png_add_test;D:/self/library/lpng1644/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
  add_test(pngstest-none-alpha "C:/Program Files/CMake/bin/cmake.exe" "-DLIBPNG=D:/self/library/lpng1644/Release/libpng16.dll" "-DTEST_COMMAND=D:/self/library/lpng1644/Release/pngstest.exe" "-P" "D:/self/library/lpng1644/tests/pngstest-none-alpha.cmake")
  set_tests_properties(pngstest-none-alpha PROPERTIES  _BACKTRACE_TRIPLES "D:/self/library/lpng1644/CMakeLists.txt;797;add_test;D:/self/library/lpng1644/CMakeLists.txt;914;png_add_test;D:/self/library/lpng1644/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Mm][Ii][Nn][Ss][Ii][Zz][Ee][Rr][Ee][Ll])$")
  add_test(pngstest-none-alpha "C:/Program Files/CMake/bin/cmake.exe" "-DLIBPNG=D:/self/library/lpng1644/MinSizeRel/libpng16.dll" "-DTEST_COMMAND=D:/self/library/lpng1644/MinSizeRel/pngstest.exe" "-P" "D:/self/library/lpng1644/tests/pngstest-none-alpha.cmake")
  set_tests_properties(pngstest-none-alpha PROPERTIES  _BACKTRACE_TRIPLES "D:/self/library/lpng1644/CMakeLists.txt;797;add_test;D:/self/library/lpng1644/CMakeLists.txt;914;png_add_test;D:/self/library/lpng1644/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
  add_test(pngstest-none-alpha "C:/Program Files/CMake/bin/cmake.exe" "-DLIBPNG=D:/self/library/lpng1644/RelWithDebInfo/libpng16.dll" "-DTEST_COMMAND=D:/self/library/lpng1644/RelWithDebInfo/pngstest.exe" "-P" "D:/self/library/lpng1644/tests/pngstest-none-alpha.cmake")
  set_tests_properties(pngstest-none-alpha PROPERTIES  _BACKTRACE_TRIPLES "D:/self/library/lpng1644/CMakeLists.txt;797;add_test;D:/self/library/lpng1644/CMakeLists.txt;914;png_add_test;D:/self/library/lpng1644/CMakeLists.txt;0;")
else()
  add_test(pngstest-none-alpha NOT_AVAILABLE)
endif()
if(CTEST_CONFIGURATION_TYPE MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
  add_test(pngstest-sRGB-none "C:/Program Files/CMake/bin/cmake.exe" "-DLIBPNG=D:/self/library/lpng1644/Debug/libpng16d.dll" "-DTEST_COMMAND=D:/self/library/lpng1644/Debug/pngstest.exe" "-P" "D:/self/library/lpng1644/tests/pngstest-sRGB-none.cmake")
  set_tests_properties(pngstest-sRGB-none PROPERTIES  _BACKTRACE_TRIPLES "D:/self/library/lpng1644/CMakeLists.txt;797;add_test;D:/self/library/lpng1644/CMakeLists.txt;914;png_add_test;D:/self/library/lpng1644/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
  add_test(pngstest-sRGB-none "C:/Program Files/CMake/bin/cmake.exe" "-DLIBPNG=D:/self/library/lpng1644/Release/libpng16.dll" "-DTEST_COMMAND=D:/self/library/lpng1644/Release/pngstest.exe" "-P" "D:/self/library/lpng1644/tests/pngstest-sRGB-none.cmake")
  set_tests_properties(pngstest-sRGB-none PROPERTIES  _BACKTRACE_TRIPLES "D:/self/library/lpng1644/CMakeLists.txt;797;add_test;D:/self/library/lpng1644/CMakeLists.txt;914;png_add_test;D:/self/library/lpng1644/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Mm][Ii][Nn][Ss][Ii][Zz][Ee][Rr][Ee][Ll])$")
  add_test(pngstest-sRGB-none "C:/Program Files/CMake/bin/cmake.exe" "-DLIBPNG=D:/self/library/lpng1644/MinSizeRel/libpng16.dll" "-DTEST_COMMAND=D:/self/library/lpng1644/MinSizeRel/pngstest.exe" "-P" "D:/self/library/lpng1644/tests/pngstest-sRGB-none.cmake")
  set_tests_properties(pngstest-sRGB-none PROPERTIES  _BACKTRACE_TRIPLES "D:/self/library/lpng1644/CMakeLists.txt;797;add_test;D:/self/library/lpng1644/CMakeLists.txt;914;png_add_test;D:/self/library/lpng1644/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
  add_test(pngstest-sRGB-none "C:/Program Files/CMake/bin/cmake.exe" "-DLIBPNG=D:/self/library/lpng1644/RelWithDebInfo/libpng16.dll" "-DTEST_COMMAND=D:/self/library/lpng1644/RelWithDebInfo/pngstest.exe" "-P" "D:/self/library/lpng1644/tests/pngstest-sRGB-none.cmake")
  set_tests_properties(pngstest-sRGB-none PROPERTIES  _BACKTRACE_TRIPLES "D:/self/library/lpng1644/CMakeLists.txt;797;add_test;D:/self/library/lpng1644/CMakeLists.txt;914;png_add_test;D:/self/library/lpng1644/CMakeLists.txt;0;")
else()
  add_test(pngstest-sRGB-none NOT_AVAILABLE)
endif()
if(CTEST_CONFIGURATION_TYPE MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
  add_test(pngstest-sRGB-alpha "C:/Program Files/CMake/bin/cmake.exe" "-DLIBPNG=D:/self/library/lpng1644/Debug/libpng16d.dll" "-DTEST_COMMAND=D:/self/library/lpng1644/Debug/pngstest.exe" "-P" "D:/self/library/lpng1644/tests/pngstest-sRGB-alpha.cmake")
  set_tests_properties(pngstest-sRGB-alpha PROPERTIES  _BACKTRACE_TRIPLES "D:/self/library/lpng1644/CMakeLists.txt;797;add_test;D:/self/library/lpng1644/CMakeLists.txt;914;png_add_test;D:/self/library/lpng1644/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
  add_test(pngstest-sRGB-alpha "C:/Program Files/CMake/bin/cmake.exe" "-DLIBPNG=D:/self/library/lpng1644/Release/libpng16.dll" "-DTEST_COMMAND=D:/self/library/lpng1644/Release/pngstest.exe" "-P" "D:/self/library/lpng1644/tests/pngstest-sRGB-alpha.cmake")
  set_tests_properties(pngstest-sRGB-alpha PROPERTIES  _BACKTRACE_TRIPLES "D:/self/library/lpng1644/CMakeLists.txt;797;add_test;D:/self/library/lpng1644/CMakeLists.txt;914;png_add_test;D:/self/library/lpng1644/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Mm][Ii][Nn][Ss][Ii][Zz][Ee][Rr][Ee][Ll])$")
  add_test(pngstest-sRGB-alpha "C:/Program Files/CMake/bin/cmake.exe" "-DLIBPNG=D:/self/library/lpng1644/MinSizeRel/libpng16.dll" "-DTEST_COMMAND=D:/self/library/lpng1644/MinSizeRel/pngstest.exe" "-P" "D:/self/library/lpng1644/tests/pngstest-sRGB-alpha.cmake")
  set_tests_properties(pngstest-sRGB-alpha PROPERTIES  _BACKTRACE_TRIPLES "D:/self/library/lpng1644/CMakeLists.txt;797;add_test;D:/self/library/lpng1644/CMakeLists.txt;914;png_add_test;D:/self/library/lpng1644/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
  add_test(pngstest-sRGB-alpha "C:/Program Files/CMake/bin/cmake.exe" "-DLIBPNG=D:/self/library/lpng1644/RelWithDebInfo/libpng16.dll" "-DTEST_COMMAND=D:/self/library/lpng1644/RelWithDebInfo/pngstest.exe" "-P" "D:/self/library/lpng1644/tests/pngstest-sRGB-alpha.cmake")
  set_tests_properties(pngstest-sRGB-alpha PROPERTIES  _BACKTRACE_TRIPLES "D:/self/library/lpng1644/CMakeLists.txt;797;add_test;D:/self/library/lpng1644/CMakeLists.txt;914;png_add_test;D:/self/library/lpng1644/CMakeLists.txt;0;")
else()
  add_test(pngstest-sRGB-alpha NOT_AVAILABLE)
endif()
if(CTEST_CONFIGURATION_TYPE MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
  add_test(pngunknown-discard "C:/Program Files/CMake/bin/cmake.exe" "-DLIBPNG=D:/self/library/lpng1644/Debug/libpng16d.dll" "-DTEST_COMMAND=D:/self/library/lpng1644/Debug/pngunknown.exe" "-P" "D:/self/library/lpng1644/tests/pngunknown-discard.cmake")
  set_tests_properties(pngunknown-discard PROPERTIES  _BACKTRACE_TRIPLES "D:/self/library/lpng1644/CMakeLists.txt;797;add_test;D:/self/library/lpng1644/CMakeLists.txt;924;png_add_test;D:/self/library/lpng1644/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
  add_test(pngunknown-discard "C:/Program Files/CMake/bin/cmake.exe" "-DLIBPNG=D:/self/library/lpng1644/Release/libpng16.dll" "-DTEST_COMMAND=D:/self/library/lpng1644/Release/pngunknown.exe" "-P" "D:/self/library/lpng1644/tests/pngunknown-discard.cmake")
  set_tests_properties(pngunknown-discard PROPERTIES  _BACKTRACE_TRIPLES "D:/self/library/lpng1644/CMakeLists.txt;797;add_test;D:/self/library/lpng1644/CMakeLists.txt;924;png_add_test;D:/self/library/lpng1644/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Mm][Ii][Nn][Ss][Ii][Zz][Ee][Rr][Ee][Ll])$")
  add_test(pngunknown-discard "C:/Program Files/CMake/bin/cmake.exe" "-DLIBPNG=D:/self/library/lpng1644/MinSizeRel/libpng16.dll" "-DTEST_COMMAND=D:/self/library/lpng1644/MinSizeRel/pngunknown.exe" "-P" "D:/self/library/lpng1644/tests/pngunknown-discard.cmake")
  set_tests_properties(pngunknown-discard PROPERTIES  _BACKTRACE_TRIPLES "D:/self/library/lpng1644/CMakeLists.txt;797;add_test;D:/self/library/lpng1644/CMakeLists.txt;924;png_add_test;D:/self/library/lpng1644/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
  add_test(pngunknown-discard "C:/Program Files/CMake/bin/cmake.exe" "-DLIBPNG=D:/self/library/lpng1644/RelWithDebInfo/libpng16.dll" "-DTEST_COMMAND=D:/self/library/lpng1644/RelWithDebInfo/pngunknown.exe" "-P" "D:/self/library/lpng1644/tests/pngunknown-discard.cmake")
  set_tests_properties(pngunknown-discard PROPERTIES  _BACKTRACE_TRIPLES "D:/self/library/lpng1644/CMakeLists.txt;797;add_test;D:/self/library/lpng1644/CMakeLists.txt;924;png_add_test;D:/self/library/lpng1644/CMakeLists.txt;0;")
else()
  add_test(pngunknown-discard NOT_AVAILABLE)
endif()
if(CTEST_CONFIGURATION_TYPE MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
  add_test(pngunknown-IDAT "C:/Program Files/CMake/bin/cmake.exe" "-DLIBPNG=D:/self/library/lpng1644/Debug/libpng16d.dll" "-DTEST_COMMAND=D:/self/library/lpng1644/Debug/pngunknown.exe" "-P" "D:/self/library/lpng1644/tests/pngunknown-IDAT.cmake")
  set_tests_properties(pngunknown-IDAT PROPERTIES  _BACKTRACE_TRIPLES "D:/self/library/lpng1644/CMakeLists.txt;797;add_test;D:/self/library/lpng1644/CMakeLists.txt;928;png_add_test;D:/self/library/lpng1644/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
  add_test(pngunknown-IDAT "C:/Program Files/CMake/bin/cmake.exe" "-DLIBPNG=D:/self/library/lpng1644/Release/libpng16.dll" "-DTEST_COMMAND=D:/self/library/lpng1644/Release/pngunknown.exe" "-P" "D:/self/library/lpng1644/tests/pngunknown-IDAT.cmake")
  set_tests_properties(pngunknown-IDAT PROPERTIES  _BACKTRACE_TRIPLES "D:/self/library/lpng1644/CMakeLists.txt;797;add_test;D:/self/library/lpng1644/CMakeLists.txt;928;png_add_test;D:/self/library/lpng1644/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Mm][Ii][Nn][Ss][Ii][Zz][Ee][Rr][Ee][Ll])$")
  add_test(pngunknown-IDAT "C:/Program Files/CMake/bin/cmake.exe" "-DLIBPNG=D:/self/library/lpng1644/MinSizeRel/libpng16.dll" "-DTEST_COMMAND=D:/self/library/lpng1644/MinSizeRel/pngunknown.exe" "-P" "D:/self/library/lpng1644/tests/pngunknown-IDAT.cmake")
  set_tests_properties(pngunknown-IDAT PROPERTIES  _BACKTRACE_TRIPLES "D:/self/library/lpng1644/CMakeLists.txt;797;add_test;D:/self/library/lpng1644/CMakeLists.txt;928;png_add_test;D:/self/library/lpng1644/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
  add_test(pngunknown-IDAT "C:/Program Files/CMake/bin/cmake.exe" "-DLIBPNG=D:/self/library/lpng1644/RelWithDebInfo/libpng16.dll" "-DTEST_COMMAND=D:/self/library/lpng1644/RelWithDebInfo/pngunknown.exe" "-P" "D:/self/library/lpng1644/tests/pngunknown-IDAT.cmake")
  set_tests_properties(pngunknown-IDAT PROPERTIES  _BACKTRACE_TRIPLES "D:/self/library/lpng1644/CMakeLists.txt;797;add_test;D:/self/library/lpng1644/CMakeLists.txt;928;png_add_test;D:/self/library/lpng1644/CMakeLists.txt;0;")
else()
  add_test(pngunknown-IDAT NOT_AVAILABLE)
endif()
if(CTEST_CONFIGURATION_TYPE MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
  add_test(pngunknown-if-safe "C:/Program Files/CMake/bin/cmake.exe" "-DLIBPNG=D:/self/library/lpng1644/Debug/libpng16d.dll" "-DTEST_COMMAND=D:/self/library/lpng1644/Debug/pngunknown.exe" "-P" "D:/self/library/lpng1644/tests/pngunknown-if-safe.cmake")
  set_tests_properties(pngunknown-if-safe PROPERTIES  _BACKTRACE_TRIPLES "D:/self/library/lpng1644/CMakeLists.txt;797;add_test;D:/self/library/lpng1644/CMakeLists.txt;932;png_add_test;D:/self/library/lpng1644/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
  add_test(pngunknown-if-safe "C:/Program Files/CMake/bin/cmake.exe" "-DLIBPNG=D:/self/library/lpng1644/Release/libpng16.dll" "-DTEST_COMMAND=D:/self/library/lpng1644/Release/pngunknown.exe" "-P" "D:/self/library/lpng1644/tests/pngunknown-if-safe.cmake")
  set_tests_properties(pngunknown-if-safe PROPERTIES  _BACKTRACE_TRIPLES "D:/self/library/lpng1644/CMakeLists.txt;797;add_test;D:/self/library/lpng1644/CMakeLists.txt;932;png_add_test;D:/self/library/lpng1644/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Mm][Ii][Nn][Ss][Ii][Zz][Ee][Rr][Ee][Ll])$")
  add_test(pngunknown-if-safe "C:/Program Files/CMake/bin/cmake.exe" "-DLIBPNG=D:/self/library/lpng1644/MinSizeRel/libpng16.dll" "-DTEST_COMMAND=D:/self/library/lpng1644/MinSizeRel/pngunknown.exe" "-P" "D:/self/library/lpng1644/tests/pngunknown-if-safe.cmake")
  set_tests_properties(pngunknown-if-safe PROPERTIES  _BACKTRACE_TRIPLES "D:/self/library/lpng1644/CMakeLists.txt;797;add_test;D:/self/library/lpng1644/CMakeLists.txt;932;png_add_test;D:/self/library/lpng1644/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
  add_test(pngunknown-if-safe "C:/Program Files/CMake/bin/cmake.exe" "-DLIBPNG=D:/self/library/lpng1644/RelWithDebInfo/libpng16.dll" "-DTEST_COMMAND=D:/self/library/lpng1644/RelWithDebInfo/pngunknown.exe" "-P" "D:/self/library/lpng1644/tests/pngunknown-if-safe.cmake")
  set_tests_properties(pngunknown-if-safe PROPERTIES  _BACKTRACE_TRIPLES "D:/self/library/lpng1644/CMakeLists.txt;797;add_test;D:/self/library/lpng1644/CMakeLists.txt;932;png_add_test;D:/self/library/lpng1644/CMakeLists.txt;0;")
else()
  add_test(pngunknown-if-safe NOT_AVAILABLE)
endif()
if(CTEST_CONFIGURATION_TYPE MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
  add_test(pngunknown-sAPI "C:/Program Files/CMake/bin/cmake.exe" "-DLIBPNG=D:/self/library/lpng1644/Debug/libpng16d.dll" "-DTEST_COMMAND=D:/self/library/lpng1644/Debug/pngunknown.exe" "-P" "D:/self/library/lpng1644/tests/pngunknown-sAPI.cmake")
  set_tests_properties(pngunknown-sAPI PROPERTIES  _BACKTRACE_TRIPLES "D:/self/library/lpng1644/CMakeLists.txt;797;add_test;D:/self/library/lpng1644/CMakeLists.txt;936;png_add_test;D:/self/library/lpng1644/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
  add_test(pngunknown-sAPI "C:/Program Files/CMake/bin/cmake.exe" "-DLIBPNG=D:/self/library/lpng1644/Release/libpng16.dll" "-DTEST_COMMAND=D:/self/library/lpng1644/Release/pngunknown.exe" "-P" "D:/self/library/lpng1644/tests/pngunknown-sAPI.cmake")
  set_tests_properties(pngunknown-sAPI PROPERTIES  _BACKTRACE_TRIPLES "D:/self/library/lpng1644/CMakeLists.txt;797;add_test;D:/self/library/lpng1644/CMakeLists.txt;936;png_add_test;D:/self/library/lpng1644/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Mm][Ii][Nn][Ss][Ii][Zz][Ee][Rr][Ee][Ll])$")
  add_test(pngunknown-sAPI "C:/Program Files/CMake/bin/cmake.exe" "-DLIBPNG=D:/self/library/lpng1644/MinSizeRel/libpng16.dll" "-DTEST_COMMAND=D:/self/library/lpng1644/MinSizeRel/pngunknown.exe" "-P" "D:/self/library/lpng1644/tests/pngunknown-sAPI.cmake")
  set_tests_properties(pngunknown-sAPI PROPERTIES  _BACKTRACE_TRIPLES "D:/self/library/lpng1644/CMakeLists.txt;797;add_test;D:/self/library/lpng1644/CMakeLists.txt;936;png_add_test;D:/self/library/lpng1644/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
  add_test(pngunknown-sAPI "C:/Program Files/CMake/bin/cmake.exe" "-DLIBPNG=D:/self/library/lpng1644/RelWithDebInfo/libpng16.dll" "-DTEST_COMMAND=D:/self/library/lpng1644/RelWithDebInfo/pngunknown.exe" "-P" "D:/self/library/lpng1644/tests/pngunknown-sAPI.cmake")
  set_tests_properties(pngunknown-sAPI PROPERTIES  _BACKTRACE_TRIPLES "D:/self/library/lpng1644/CMakeLists.txt;797;add_test;D:/self/library/lpng1644/CMakeLists.txt;936;png_add_test;D:/self/library/lpng1644/CMakeLists.txt;0;")
else()
  add_test(pngunknown-sAPI NOT_AVAILABLE)
endif()
if(CTEST_CONFIGURATION_TYPE MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
  add_test(pngunknown-save "C:/Program Files/CMake/bin/cmake.exe" "-DLIBPNG=D:/self/library/lpng1644/Debug/libpng16d.dll" "-DTEST_COMMAND=D:/self/library/lpng1644/Debug/pngunknown.exe" "-P" "D:/self/library/lpng1644/tests/pngunknown-save.cmake")
  set_tests_properties(pngunknown-save PROPERTIES  _BACKTRACE_TRIPLES "D:/self/library/lpng1644/CMakeLists.txt;797;add_test;D:/self/library/lpng1644/CMakeLists.txt;940;png_add_test;D:/self/library/lpng1644/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
  add_test(pngunknown-save "C:/Program Files/CMake/bin/cmake.exe" "-DLIBPNG=D:/self/library/lpng1644/Release/libpng16.dll" "-DTEST_COMMAND=D:/self/library/lpng1644/Release/pngunknown.exe" "-P" "D:/self/library/lpng1644/tests/pngunknown-save.cmake")
  set_tests_properties(pngunknown-save PROPERTIES  _BACKTRACE_TRIPLES "D:/self/library/lpng1644/CMakeLists.txt;797;add_test;D:/self/library/lpng1644/CMakeLists.txt;940;png_add_test;D:/self/library/lpng1644/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Mm][Ii][Nn][Ss][Ii][Zz][Ee][Rr][Ee][Ll])$")
  add_test(pngunknown-save "C:/Program Files/CMake/bin/cmake.exe" "-DLIBPNG=D:/self/library/lpng1644/MinSizeRel/libpng16.dll" "-DTEST_COMMAND=D:/self/library/lpng1644/MinSizeRel/pngunknown.exe" "-P" "D:/self/library/lpng1644/tests/pngunknown-save.cmake")
  set_tests_properties(pngunknown-save PROPERTIES  _BACKTRACE_TRIPLES "D:/self/library/lpng1644/CMakeLists.txt;797;add_test;D:/self/library/lpng1644/CMakeLists.txt;940;png_add_test;D:/self/library/lpng1644/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
  add_test(pngunknown-save "C:/Program Files/CMake/bin/cmake.exe" "-DLIBPNG=D:/self/library/lpng1644/RelWithDebInfo/libpng16.dll" "-DTEST_COMMAND=D:/self/library/lpng1644/RelWithDebInfo/pngunknown.exe" "-P" "D:/self/library/lpng1644/tests/pngunknown-save.cmake")
  set_tests_properties(pngunknown-save PROPERTIES  _BACKTRACE_TRIPLES "D:/self/library/lpng1644/CMakeLists.txt;797;add_test;D:/self/library/lpng1644/CMakeLists.txt;940;png_add_test;D:/self/library/lpng1644/CMakeLists.txt;0;")
else()
  add_test(pngunknown-save NOT_AVAILABLE)
endif()
if(CTEST_CONFIGURATION_TYPE MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
  add_test(pngunknown-sTER "C:/Program Files/CMake/bin/cmake.exe" "-DLIBPNG=D:/self/library/lpng1644/Debug/libpng16d.dll" "-DTEST_COMMAND=D:/self/library/lpng1644/Debug/pngunknown.exe" "-P" "D:/self/library/lpng1644/tests/pngunknown-sTER.cmake")
  set_tests_properties(pngunknown-sTER PROPERTIES  _BACKTRACE_TRIPLES "D:/self/library/lpng1644/CMakeLists.txt;797;add_test;D:/self/library/lpng1644/CMakeLists.txt;944;png_add_test;D:/self/library/lpng1644/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
  add_test(pngunknown-sTER "C:/Program Files/CMake/bin/cmake.exe" "-DLIBPNG=D:/self/library/lpng1644/Release/libpng16.dll" "-DTEST_COMMAND=D:/self/library/lpng1644/Release/pngunknown.exe" "-P" "D:/self/library/lpng1644/tests/pngunknown-sTER.cmake")
  set_tests_properties(pngunknown-sTER PROPERTIES  _BACKTRACE_TRIPLES "D:/self/library/lpng1644/CMakeLists.txt;797;add_test;D:/self/library/lpng1644/CMakeLists.txt;944;png_add_test;D:/self/library/lpng1644/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Mm][Ii][Nn][Ss][Ii][Zz][Ee][Rr][Ee][Ll])$")
  add_test(pngunknown-sTER "C:/Program Files/CMake/bin/cmake.exe" "-DLIBPNG=D:/self/library/lpng1644/MinSizeRel/libpng16.dll" "-DTEST_COMMAND=D:/self/library/lpng1644/MinSizeRel/pngunknown.exe" "-P" "D:/self/library/lpng1644/tests/pngunknown-sTER.cmake")
  set_tests_properties(pngunknown-sTER PROPERTIES  _BACKTRACE_TRIPLES "D:/self/library/lpng1644/CMakeLists.txt;797;add_test;D:/self/library/lpng1644/CMakeLists.txt;944;png_add_test;D:/self/library/lpng1644/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
  add_test(pngunknown-sTER "C:/Program Files/CMake/bin/cmake.exe" "-DLIBPNG=D:/self/library/lpng1644/RelWithDebInfo/libpng16.dll" "-DTEST_COMMAND=D:/self/library/lpng1644/RelWithDebInfo/pngunknown.exe" "-P" "D:/self/library/lpng1644/tests/pngunknown-sTER.cmake")
  set_tests_properties(pngunknown-sTER PROPERTIES  _BACKTRACE_TRIPLES "D:/self/library/lpng1644/CMakeLists.txt;797;add_test;D:/self/library/lpng1644/CMakeLists.txt;944;png_add_test;D:/self/library/lpng1644/CMakeLists.txt;0;")
else()
  add_test(pngunknown-sTER NOT_AVAILABLE)
endif()
if(CTEST_CONFIGURATION_TYPE MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
  add_test(pngunknown-vpAg "C:/Program Files/CMake/bin/cmake.exe" "-DLIBPNG=D:/self/library/lpng1644/Debug/libpng16d.dll" "-DTEST_COMMAND=D:/self/library/lpng1644/Debug/pngunknown.exe" "-P" "D:/self/library/lpng1644/tests/pngunknown-vpAg.cmake")
  set_tests_properties(pngunknown-vpAg PROPERTIES  _BACKTRACE_TRIPLES "D:/self/library/lpng1644/CMakeLists.txt;797;add_test;D:/self/library/lpng1644/CMakeLists.txt;948;png_add_test;D:/self/library/lpng1644/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
  add_test(pngunknown-vpAg "C:/Program Files/CMake/bin/cmake.exe" "-DLIBPNG=D:/self/library/lpng1644/Release/libpng16.dll" "-DTEST_COMMAND=D:/self/library/lpng1644/Release/pngunknown.exe" "-P" "D:/self/library/lpng1644/tests/pngunknown-vpAg.cmake")
  set_tests_properties(pngunknown-vpAg PROPERTIES  _BACKTRACE_TRIPLES "D:/self/library/lpng1644/CMakeLists.txt;797;add_test;D:/self/library/lpng1644/CMakeLists.txt;948;png_add_test;D:/self/library/lpng1644/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Mm][Ii][Nn][Ss][Ii][Zz][Ee][Rr][Ee][Ll])$")
  add_test(pngunknown-vpAg "C:/Program Files/CMake/bin/cmake.exe" "-DLIBPNG=D:/self/library/lpng1644/MinSizeRel/libpng16.dll" "-DTEST_COMMAND=D:/self/library/lpng1644/MinSizeRel/pngunknown.exe" "-P" "D:/self/library/lpng1644/tests/pngunknown-vpAg.cmake")
  set_tests_properties(pngunknown-vpAg PROPERTIES  _BACKTRACE_TRIPLES "D:/self/library/lpng1644/CMakeLists.txt;797;add_test;D:/self/library/lpng1644/CMakeLists.txt;948;png_add_test;D:/self/library/lpng1644/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
  add_test(pngunknown-vpAg "C:/Program Files/CMake/bin/cmake.exe" "-DLIBPNG=D:/self/library/lpng1644/RelWithDebInfo/libpng16.dll" "-DTEST_COMMAND=D:/self/library/lpng1644/RelWithDebInfo/pngunknown.exe" "-P" "D:/self/library/lpng1644/tests/pngunknown-vpAg.cmake")
  set_tests_properties(pngunknown-vpAg PROPERTIES  _BACKTRACE_TRIPLES "D:/self/library/lpng1644/CMakeLists.txt;797;add_test;D:/self/library/lpng1644/CMakeLists.txt;948;png_add_test;D:/self/library/lpng1644/CMakeLists.txt;0;")
else()
  add_test(pngunknown-vpAg NOT_AVAILABLE)
endif()
if(CTEST_CONFIGURATION_TYPE MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
  add_test(pngimage-quick "C:/Program Files/CMake/bin/cmake.exe" "-DLIBPNG=D:/self/library/lpng1644/Debug/libpng16d.dll" "-DTEST_COMMAND=D:/self/library/lpng1644/Debug/pngimage.exe" "-P" "D:/self/library/lpng1644/tests/pngimage-quick.cmake")
  set_tests_properties(pngimage-quick PROPERTIES  _BACKTRACE_TRIPLES "D:/self/library/lpng1644/CMakeLists.txt;797;add_test;D:/self/library/lpng1644/CMakeLists.txt;956;png_add_test;D:/self/library/lpng1644/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
  add_test(pngimage-quick "C:/Program Files/CMake/bin/cmake.exe" "-DLIBPNG=D:/self/library/lpng1644/Release/libpng16.dll" "-DTEST_COMMAND=D:/self/library/lpng1644/Release/pngimage.exe" "-P" "D:/self/library/lpng1644/tests/pngimage-quick.cmake")
  set_tests_properties(pngimage-quick PROPERTIES  _BACKTRACE_TRIPLES "D:/self/library/lpng1644/CMakeLists.txt;797;add_test;D:/self/library/lpng1644/CMakeLists.txt;956;png_add_test;D:/self/library/lpng1644/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Mm][Ii][Nn][Ss][Ii][Zz][Ee][Rr][Ee][Ll])$")
  add_test(pngimage-quick "C:/Program Files/CMake/bin/cmake.exe" "-DLIBPNG=D:/self/library/lpng1644/MinSizeRel/libpng16.dll" "-DTEST_COMMAND=D:/self/library/lpng1644/MinSizeRel/pngimage.exe" "-P" "D:/self/library/lpng1644/tests/pngimage-quick.cmake")
  set_tests_properties(pngimage-quick PROPERTIES  _BACKTRACE_TRIPLES "D:/self/library/lpng1644/CMakeLists.txt;797;add_test;D:/self/library/lpng1644/CMakeLists.txt;956;png_add_test;D:/self/library/lpng1644/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
  add_test(pngimage-quick "C:/Program Files/CMake/bin/cmake.exe" "-DLIBPNG=D:/self/library/lpng1644/RelWithDebInfo/libpng16.dll" "-DTEST_COMMAND=D:/self/library/lpng1644/RelWithDebInfo/pngimage.exe" "-P" "D:/self/library/lpng1644/tests/pngimage-quick.cmake")
  set_tests_properties(pngimage-quick PROPERTIES  _BACKTRACE_TRIPLES "D:/self/library/lpng1644/CMakeLists.txt;797;add_test;D:/self/library/lpng1644/CMakeLists.txt;956;png_add_test;D:/self/library/lpng1644/CMakeLists.txt;0;")
else()
  add_test(pngimage-quick NOT_AVAILABLE)
endif()
if(CTEST_CONFIGURATION_TYPE MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
  add_test(pngimage-full "C:/Program Files/CMake/bin/cmake.exe" "-DLIBPNG=D:/self/library/lpng1644/Debug/libpng16d.dll" "-DTEST_COMMAND=D:/self/library/lpng1644/Debug/pngimage.exe" "-P" "D:/self/library/lpng1644/tests/pngimage-full.cmake")
  set_tests_properties(pngimage-full PROPERTIES  _BACKTRACE_TRIPLES "D:/self/library/lpng1644/CMakeLists.txt;797;add_test;D:/self/library/lpng1644/CMakeLists.txt;960;png_add_test;D:/self/library/lpng1644/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
  add_test(pngimage-full "C:/Program Files/CMake/bin/cmake.exe" "-DLIBPNG=D:/self/library/lpng1644/Release/libpng16.dll" "-DTEST_COMMAND=D:/self/library/lpng1644/Release/pngimage.exe" "-P" "D:/self/library/lpng1644/tests/pngimage-full.cmake")
  set_tests_properties(pngimage-full PROPERTIES  _BACKTRACE_TRIPLES "D:/self/library/lpng1644/CMakeLists.txt;797;add_test;D:/self/library/lpng1644/CMakeLists.txt;960;png_add_test;D:/self/library/lpng1644/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Mm][Ii][Nn][Ss][Ii][Zz][Ee][Rr][Ee][Ll])$")
  add_test(pngimage-full "C:/Program Files/CMake/bin/cmake.exe" "-DLIBPNG=D:/self/library/lpng1644/MinSizeRel/libpng16.dll" "-DTEST_COMMAND=D:/self/library/lpng1644/MinSizeRel/pngimage.exe" "-P" "D:/self/library/lpng1644/tests/pngimage-full.cmake")
  set_tests_properties(pngimage-full PROPERTIES  _BACKTRACE_TRIPLES "D:/self/library/lpng1644/CMakeLists.txt;797;add_test;D:/self/library/lpng1644/CMakeLists.txt;960;png_add_test;D:/self/library/lpng1644/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
  add_test(pngimage-full "C:/Program Files/CMake/bin/cmake.exe" "-DLIBPNG=D:/self/library/lpng1644/RelWithDebInfo/libpng16.dll" "-DTEST_COMMAND=D:/self/library/lpng1644/RelWithDebInfo/pngimage.exe" "-P" "D:/self/library/lpng1644/tests/pngimage-full.cmake")
  set_tests_properties(pngimage-full PROPERTIES  _BACKTRACE_TRIPLES "D:/self/library/lpng1644/CMakeLists.txt;797;add_test;D:/self/library/lpng1644/CMakeLists.txt;960;png_add_test;D:/self/library/lpng1644/CMakeLists.txt;0;")
else()
  add_test(pngimage-full NOT_AVAILABLE)
endif()
